
[encoder]
	#How many pattern slots should the Package Recipe Encoder have.
	#Warning: Changing this value when world is running may cause client crashes.
	#Range: 1 ~ 20
	pattern_slots = 20
	#The list of recipe types to disable in the Package Recipe Encoder.
	disabled_recipe_types = []

[packager]
	#How much FE the Packager should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Packager should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Packager can use.
	#Range: > 0
	energy_usage = 100
	#How many ticks should the Packager wait between each refresh.
	#Range: 1 ~ 40
	refresh_interval = 4
	#Should the Packager draw energy from ME systems.
	draw_me_energy = true

[packager_extension]
	#How much FE the Packager Extension should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Packager Extension should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Packager Extension can use.
	#Range: > 0
	energy_usage = 100
	#How many ticks should the Packager Extension wait between each refresh.
	#Range: 1 ~ 40
	refresh_interval = 4
	#Should the Packager Extension draw energy from ME systems.
	draw_me_energy = true

[unpackager]
	#How much FE the Unpackager should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Unpackager should use per operation.
	#Range: > 0
	energy_usage = 50
	#How many ticks should the Unpackager wait between each refresh.
	#Range: 1 ~ 40
	refresh_interval = 4
	#Should the Unpackager draw energy from ME systems.
	draw_me_energy = true

[distributor]
	#How large the range of the Positioned Package Distributor should be.
	#Range: > 1
	range = 16
	#How many ticks should the Positioned Package Distributor wait between each refresh.
	#Range: 1 ~ 40
	refresh_interval = 4

	[distributor.crafting_proxy]
		#How large the range of the Package Crafting Machine Proxy should be.
		#Range: > 1
		range = 8

		[distributor.crafting_proxy.crafter]
			#How much FE the Package Crafter should hold.
			#Range: > 0
			energy_capacity = 5000
			#How much total FE the Package Crafter should use per operation.
			#Range: > 0
			energy_req = 500
			#How much FE/t maximum the Package Crafter can use.
			#Range: > 0
			energy_usage = 100
			#How many ticks should the Package Crafter wait between each refresh.
			#Range: 1 ~ 40
			refresh_interval = 4
			#Should the Package Crafter draw energy from ME systems.
			draw_me_energy = true

		[distributor.crafting_proxy.fluid_package_filler]
			#How much FE the Fluid Package Filler should hold.
			#Range: > 0
			energy_capacity = 5000
			#How much total FE the Fluid Package Filler should use per operation.
			#Range: > 0
			energy_req = 500
			#How many ticks should the Fluid Package Filler wait between each refresh.
			#Range: 1 ~ 40
			refresh_interval = 4
			#How much FE/t maximum the Fluid Package Filler can use.
			#Range: > 0
			energy_usage = 100

